services:
  - type: web
    name: talklive
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: GOOGLE_CLIENT_ID
        sync: false
