'use strict';
/*
 * Shared plumbing for the TalkLive Journal: the ten long-form articles under
 * /blog/, the journal front page, and the /languages/ feature.
 *
 * Every page here is hand-designed. Each article brings its own typography and
 * layout (its `css`); this file only supplies what has to be identical on all
 * of them - the <head> metadata, a quiet masthead, the legal footer, one ad
 * slot, and the @font-face rules for the self-hosted fonts in
 * public/fonts/mag/ (the site CSP allows fonts from 'self' only, so Google
 * Fonts cannot be used).
 *
 * Every page also carries the start-talking component (ctaHero / ctaDock):
 * readers who arrive from ChatGPT or search on a region or language feature
 * are mostly looking for someone to talk to, so the way in has to be the
 * first thing they see and never more than a thumb away.
 */
const fs = require('fs');
const path = require('path');

const SITE = 'https://talklive.app';
const PUBLIC = path.join(__dirname, '..', '..', 'public');
const OG_IMAGE = `${SITE}/og-image.png?v=2`;
const CSS_VERSION = '20261006themed';
const CTA_JS_VERSION = '20261006nolive';

// family -> [ [weight, style, file] ]
const FONTS = {
  'Abril Fatface': [[400, 'normal', 'abril-fatface-latin-400-normal']],
  'Anton': [[400, 'normal', 'anton-latin-400-normal']],
  'Bebas Neue': [[400, 'normal', 'bebas-neue-latin-400-normal']],
  'Big Shoulders Display': [[600, 'normal', 'big-shoulders-display-latin-600-normal'], [800, 'normal', 'big-shoulders-display-latin-800-normal']],
  'Bricolage Grotesque': [[400, 'normal', 'bricolage-grotesque-latin-400-normal'], [700, 'normal', 'bricolage-grotesque-latin-700-normal']],
  'Courier Prime': [[400, 'normal', 'courier-prime-latin-400-normal'], [700, 'normal', 'courier-prime-latin-700-normal']],
  'Instrument Serif': [[400, 'normal', 'instrument-serif-latin-400-normal'], [400, 'italic', 'instrument-serif-latin-400-italic']],
  'Nunito': [[400, 'normal', 'nunito-latin-400-normal'], [800, 'normal', 'nunito-latin-800-normal']],
  'Manrope': [[400, 'normal', 'manrope-latin-400-normal'], [700, 'normal', 'manrope-latin-700-normal']],
  'Syne': [[800, 'normal', 'syne-latin-800-normal']],
  'Unbounded': [[500, 'normal', 'unbounded-latin-500-normal'], [800, 'normal', 'unbounded-latin-800-normal']],
  'Archivo Black': [[400, 'normal', 'archivo-black-latin-400-normal']],
  'Archivo': [[400, 'normal', 'archivo-latin-400-normal'], [600, 'normal', 'archivo-latin-600-normal']],
  'Caveat': [[500, 'normal', 'caveat-latin-500-normal']],
  'Cormorant Garamond': [[500, 'normal', 'cormorant-garamond-latin-500-normal'], [500, 'italic', 'cormorant-garamond-latin-500-italic'], [700, 'normal', 'cormorant-garamond-latin-700-normal']],
  'DM Sans': [[400, 'normal', 'dm-sans-latin-400-normal'], [500, 'normal', 'dm-sans-latin-500-normal']],
  'DM Serif Display': [[400, 'normal', 'dm-serif-display-latin-400-normal'], [400, 'italic', 'dm-serif-display-latin-400-italic']],
  'Fraunces': [[400, 'normal', 'fraunces-latin-400-normal'], [400, 'italic', 'fraunces-latin-400-italic'], [700, 'normal', 'fraunces-latin-700-normal']],
  'IBM Plex Sans': [[500, 'normal', 'ibm-plex-sans-latin-500-normal']],
  'IBM Plex Serif': [[400, 'normal', 'ibm-plex-serif-latin-400-normal'], [400, 'italic', 'ibm-plex-serif-latin-400-italic'], [600, 'normal', 'ibm-plex-serif-latin-600-normal']],
  'Inter': [[400, 'normal', 'inter-latin-400-normal'], [600, 'normal', 'inter-latin-600-normal']],
  'JetBrains Mono': [[400, 'normal', 'jetbrains-mono-latin-400-normal']],
  'Libre Caslon Text': [[400, 'normal', 'libre-caslon-text-latin-400-normal'], [400, 'italic', 'libre-caslon-text-latin-400-italic'], [700, 'normal', 'libre-caslon-text-latin-700-normal']],
  'Literata': [[400, 'normal', 'literata-latin-400-normal'], [400, 'italic', 'literata-latin-400-italic'], [700, 'normal', 'literata-latin-700-normal']],
  'Lora': [[400, 'normal', 'lora-latin-400-normal'], [400, 'italic', 'lora-latin-400-italic'], [700, 'normal', 'lora-latin-700-normal']],
  'Old Standard TT': [[700, 'normal', 'old-standard-tt-latin-700-normal']],
  'Playfair Display': [[700, 'normal', 'playfair-display-latin-700-normal'], [400, 'italic', 'playfair-display-latin-400-italic']],
  'Source Serif 4': [[400, 'normal', 'source-serif-4-latin-400-normal'], [400, 'italic', 'source-serif-4-latin-400-italic'], [600, 'normal', 'source-serif-4-latin-600-normal']],
  'Space Grotesk': [[400, 'normal', 'space-grotesk-latin-400-normal'], [700, 'normal', 'space-grotesk-latin-700-normal']],
};

function journalCss() {
  const faces = Object.entries(FONTS).flatMap(([family, list]) => list.map(([w, s, file]) =>
    `@font-face{font-family:"${family}";font-style:${s};font-weight:${w};font-display:swap;src:url(/fonts/mag/${file}.woff2) format("woff2")}`));
  return `/* TalkLive Journal - generated by scripts/journal/shared.js. Do not edit. */
${faces.join('\n')}
*,*::before,*::after{box-sizing:border-box}
html{-webkit-text-size-adjust:100%;text-size-adjust:100%}
body{margin:0;background:var(--paper,#fff);color:var(--ink,#111);text-rendering:optimizeLegibility;-webkit-font-smoothing:antialiased}
img,svg{max-width:100%;height:auto}
a{color:inherit}
.skip{position:absolute;left:-9999px}.skip:focus{left:12px;top:12px;background:#fff;color:#000;padding:8px 12px;z-index:9}
.j-mast{display:flex;align-items:center;justify-content:space-between;gap:16px;max-width:1120px;margin:0 auto;padding:14px 20px;font:500 13px/1.2 system-ui,-apple-system,"Segoe UI",sans-serif;letter-spacing:.04em;color:var(--mast,currentColor);border-bottom:1px solid var(--rule,rgba(0,0,0,.12))}
.j-mast a{text-decoration:none}
.j-mast .j-brand{font-weight:600;text-transform:uppercase;letter-spacing:.14em;white-space:nowrap}
.j-mast nav{display:flex;gap:18px;flex-wrap:wrap}
.j-mast nav a{opacity:.75}.j-mast nav a:hover{opacity:1;text-decoration:underline}
.j-foot{max-width:1120px;margin:72px auto 0;padding:28px 20px 40px;border-top:1px solid var(--rule,rgba(0,0,0,.12));font:400 13px/1.7 system-ui,-apple-system,"Segoe UI",sans-serif;color:var(--mast,currentColor)}
.j-foot nav{display:flex;flex-wrap:wrap;gap:6px 18px;margin-bottom:10px}
.j-foot a{opacity:.8}
.j-foot p{margin:0;opacity:.6}
.j-more{max-width:1120px;margin:64px auto 0;padding:0 20px}
.j-more h2{font:600 12px/1 system-ui,-apple-system,"Segoe UI",sans-serif;letter-spacing:.16em;text-transform:uppercase;margin:0 0 14px;opacity:.7}
.j-more ul{list-style:none;margin:0;padding:0;display:grid;gap:12px;grid-template-columns:repeat(auto-fit,minmax(220px,1fr))}
.j-more li{border-top:1px solid var(--rule,rgba(0,0,0,.12));padding-top:10px}
.j-more a{text-decoration:none;font:inherit}
.j-more a:hover{text-decoration:underline}
.ad-card{max-width:728px;margin:48px auto;padding:10px 0 0;border-top:1px solid var(--rule,rgba(0,0,0,.12));text-align:center}
.ad-card-label{display:block;font:500 10px/1 system-ui,-apple-system,"Segoe UI",sans-serif;letter-spacing:.18em;text-transform:uppercase;opacity:.5;margin-bottom:8px}
@media (max-width:640px){.j-mast{flex-wrap:wrap;gap:8px 14px;font-size:12px}.j-mast nav{gap:14px}}
/* Start-talking buttons. No box of their own: they sit on the page's paper in
   the page's type, so they read as part of the article rather than an ad.
   Colours come from --cta-* (set per page by ctaVars), with safe defaults. */
.tl-go{max-width:720px;margin:34px auto;padding:0 20px;text-align:center;color:inherit}
.tl-go-wide{max-width:900px}
.tl-go h2.tl-go-h{margin:0 0 6px;font-family:inherit;font-weight:700;font-size:clamp(22px,3vw,28px);line-height:1.2;color:inherit;letter-spacing:-.005em}
.tl-go p.tl-go-sub{margin:0 auto 16px;max-width:560px;font-size:16px;line-height:1.5;opacity:.78}
.tl-go .tl-go-row{display:flex;gap:12px;flex-wrap:wrap}
.tl-go a.tl-go-btn,.tl-dock a.tl-go-btn{position:relative;flex:1 1 220px;display:flex;align-items:center;justify-content:center;gap:12px;min-height:66px;padding:12px 22px;border-radius:999px;border:0;text-decoration:none!important;font:700 20px/1.1 system-ui,-apple-system,"Segoe UI",sans-serif;letter-spacing:-.005em;-webkit-tap-highlight-color:transparent;touch-action:manipulation;user-select:none;transition:transform .12s ease,box-shadow .2s ease,filter .2s ease}
.tl-go-btn svg{width:26px;height:26px;flex:none}
.tl-go-btn small{display:block;font:500 12px/1.2 system-ui,-apple-system,sans-serif;opacity:.85;margin-top:3px}
.tl-go-btn .tl-go-txt{text-align:left}
.tl-go-btn .tl-go-arr{margin-left:auto;transition:transform .2s ease}
.tl-go-talk{background:var(--cta-talk,#1f8a4c);color:var(--cta-talk-ink,#fff)!important;box-shadow:0 8px 22px -10px var(--cta-talk,#1f8a4c)}
.tl-go-chat{background:var(--cta-chat,#2b2b2b);color:var(--cta-chat-ink,#fff)!important;box-shadow:0 8px 22px -10px var(--cta-chat,#2b2b2b)}
.tl-go-talk::before{content:"";position:absolute;inset:0;border-radius:inherit;animation:tlPulse 2.2s infinite;pointer-events:none}
.tl-go-btn:hover{filter:brightness(1.07);transform:translateY(-2px)}
.tl-go-btn:hover .tl-go-arr{transform:translateX(4px)}
.tl-go-btn:active,.tl-go-btn.is-press{transform:scale(.96);filter:brightness(.95)}
.tl-go-btn:focus-visible{outline:3px solid currentColor;outline-offset:3px}
.tl-go p.tl-go-fine{margin:12px 0 0;font:500 12.5px/1.4 system-ui,-apple-system,sans-serif;opacity:.6}
.tl-dock{position:fixed;left:0;right:0;bottom:0;z-index:60;display:flex;gap:10px;padding:10px 12px calc(10px + env(safe-area-inset-bottom));background:var(--paper,#fff);border-top:1px solid var(--rule,rgba(0,0,0,.12));box-shadow:0 -8px 24px -18px rgba(0,0,0,.35);transform:translateY(115%);transition:transform .28s cubic-bezier(.2,.8,.2,1)}
.tl-dock.is-on{transform:none}
.tl-dock a.tl-go-btn{flex:1 1 0;min-width:0;min-height:52px;padding:8px 12px;font-size:17px;gap:8px}
.tl-dock .tl-go-btn svg{width:22px;height:22px}
.tl-dock .tl-go-btn small,.tl-dock .tl-go-arr{display:none}
.tl-dock .tl-go-txt{white-space:nowrap}
body.tl-has-dock{padding-bottom:80px}
@media (min-width:900px){.tl-dock{left:50%;right:auto;bottom:18px;width:520px;transform:translate(-50%,140%);border-radius:999px;border:1px solid var(--rule,rgba(0,0,0,.12));padding:8px;box-shadow:0 14px 36px -16px rgba(0,0,0,.4)}.tl-dock.is-on{transform:translate(-50%,0)}body.tl-has-dock{padding-bottom:0}}
@media (max-width:480px){.tl-go{margin:26px auto;padding:0 16px}.tl-go-btn{flex-basis:100%;min-height:62px;font-size:19px}}
@keyframes tlPulse{0%{box-shadow:0 0 0 0 color-mix(in srgb,var(--cta-talk,#1f8a4c) 55%,transparent)}70%{box-shadow:0 0 0 14px color-mix(in srgb,var(--cta-talk,#1f8a4c) 0%,transparent)}100%{box-shadow:0 0 0 0 transparent}}
@media (prefers-reduced-motion:reduce){.tl-go-talk::before{animation:none}.tl-go-btn,.tl-dock{transition:none}}
`;
}

function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function words(html) {
  return html.replace(/<style[\s\S]*?<\/style>/g, '').replace(/<[^>]+>/g, ' ').split(/\s+/).filter(Boolean).length;
}

// Preload only the faces the page leads with, so the headline does not swap.
function preloads(files) {
  return (files || []).map(f => `<link rel="preload" href="/fonts/mag/${f}.woff2" as="font" type="font/woff2" crossorigin />`).join('\n');
}

function head(p) {
  const canonical = `${SITE}${p.path}`;
  const ld = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'Organization', '@id': `${SITE}/#organization`, name: 'TalkLive', url: `${SITE}/`,
        logo: { '@type': 'ImageObject', url: `${SITE}/favicon-192.png`, width: 192, height: 192 },
      },
      p.article ? {
        '@type': 'Article', '@id': `${canonical}#article`, headline: p.h1, description: p.description,
        datePublished: p.date, dateModified: p.updated || p.date, inLanguage: 'en',
        mainEntityOfPage: canonical, image: OG_IMAGE, wordCount: p.wordCount,
        author: { '@type': 'Organization', name: 'TalkLive Journal', url: `${SITE}/blog/` },
        publisher: { '@id': `${SITE}/#organization` },
        articleSection: p.tag,
      } : {
        '@type': 'CollectionPage', '@id': `${canonical}#webpage`, name: p.title, description: p.description, url: canonical,
        publisher: { '@id': `${SITE}/#organization` },
      },
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Home', item: `${SITE}/` },
          { '@type': 'ListItem', position: 2, name: 'Journal', item: `${SITE}/blog/` },
        ].concat(p.path === '/blog/' ? [] : [{ '@type': 'ListItem', position: 3, name: p.crumb || p.h1, item: canonical }]),
      },
    ],
  };
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
<title>${esc(p.title)}</title>
<meta name="description" content="${esc(p.description)}" />
<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1" />
<meta name="theme-color" content="${p.theme || '#ffffff'}" />
<meta name="author" content="TalkLive Journal" />
<link rel="canonical" href="${canonical}" />
<link rel="alternate" type="application/rss+xml" title="TalkLive Journal" href="${SITE}/blog/feed.xml" />
<meta property="og:type" content="${p.article ? 'article' : 'website'}" />
<meta property="og:site_name" content="TalkLive" />
<meta property="og:title" content="${esc(p.h1)}" />
<meta property="og:description" content="${esc(p.description)}" />
<meta property="og:url" content="${canonical}" />
<meta property="og:image" content="${OG_IMAGE}" />
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="630" />
<meta property="og:image:alt" content="${esc(p.h1)} - TalkLive Journal" />
<meta property="og:locale" content="en_US" />
${p.article ? `<meta property="article:published_time" content="${p.date}" />
<meta property="article:modified_time" content="${p.updated || p.date}" />
<meta property="article:section" content="${esc(p.tag)}" />
` : ''}<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="${esc(p.h1)}" />
<meta name="twitter:description" content="${esc(p.description)}" />
<meta name="twitter:image" content="${OG_IMAGE}" />
<meta name="twitter:image:alt" content="${esc(p.h1)} - TalkLive Journal" />
<link rel="icon" href="/favicon.svg" type="image/svg+xml" />
<link rel="apple-touch-icon" href="/favicon-192.png" />
<link rel="manifest" href="/site.webmanifest" />
${preloads(p.preload)}
<link rel="stylesheet" href="/journal.css?v=${CSS_VERSION}" />
<style>${p.css}${ctaVars(p.slug || (p.path === '/blog/' ? 'blog' : ''))}</style>
<script defer src="/pwa.js?v=20260908pwa"></script>
<script type="application/ld+json">${JSON.stringify(ld)}</script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5162304231095978"
     crossorigin="anonymous"></script>
<script defer src="/ads.js?v=20260923adsense2"></script>
</head>`;
}

function masthead() {
  return `<a class="skip" href="#story">Skip to the article</a>
<header class="j-mast">
  <a class="j-brand" href="/blog/">TalkLive Journal</a>
  <nav aria-label="Journal"><a href="/blog/">All stories</a><a href="/languages/">Languages</a><a href="/about">About</a><a href="/">TalkLive</a></nav>
</header>`;
}

function footer() {
  return `<footer class="j-foot">
  <nav aria-label="Site"><a href="/about">About</a><a href="/contact">Contact</a><a href="/privacy">Privacy Policy</a><a href="/terms">Terms</a><a href="/community-guidelines">Community Guidelines</a><a href="/safety">Safety</a><a href="/">TalkLive home</a></nav>
  <p>&copy; ${new Date().getFullYear()} TalkLive. The Journal is written by the TalkLive team. Corrections: info@talklive.app</p>
</footer>`;
}

function ad() {
  return `<div class="ad-card"><span class="ad-card-label">Advertisement</span><div data-ad="native"></div></div>`;
}

// Per-page button colours: Call is always a green that belongs to the page's
// palette, Chat takes the page's own accent. [talk, talkInk, chat, chatInk].
const CTA_THEMES = {
  // Journal
  'blog': ['#2f6b3f', '#fff', '#8a2b1e', '#fff'],
  'why-talking-to-strangers-feels-easier': ['#2f6b3f', '#fff', '#8a2b1e', '#fff'],
  'what-happened-to-omegle': ['#2f7a4a', '#fff', '#141414', '#efece4'],
  'science-of-talking-to-strangers': ['#1f8a4c', '#fff', '#0f4c81', '#fff'],
  'loneliness-what-actually-helps': ['#5fbf86', '#0e1a12', '#d8b46a', '#1b2130'],
  'how-random-matchmaking-works': ['#1f8f4e', '#fff', '#ff4f1f', '#101112'],
  'how-to-be-a-good-listener': ['#1f5c45', '#fff', '#1c1f1b', '#fbfaf6'],
  'phone-anxiety-how-to-get-comfortable-talking': ['#2e7d5b', '#fff', '#9c3d54', '#fff'],
  'how-to-practise-a-language-by-speaking': ['#2e8b57', '#fff', '#2f5d8a', '#fff'],
  'how-to-spot-a-bot-or-scam-in-random-chat': ['#3ddc84', '#0b1a10', '#ffd23f', '#17181a'],
  'what-to-talk-about-with-a-stranger': ['#1a9b4b', '#fff', '#e10600', '#fff'],
  // Regions and the languages feature
  'africa': ['#0f7b4a', '#fff', '#c2522d', '#fff'],
  'americas': ['#2a8f5c', '#fff', '#1d2a4a', '#fff'],
  'europe': ['#1a7f5a', '#fff', '#990f3d', '#fff'],
  'middle-east': ['#2e7d5b', '#fff', '#101a33', '#f3ead6'],
  'south-asia': ['#3a7d44', '#fff', '#2d2f6b', '#fff'],
  'southeast-asia': ['#2f8f5b', '#fff', '#d9472b', '#fff'],
  'languages': ['#2a7f5f', '#fff', '#c8553d', '#fff'],
  // Country guides
  'bangladesh': ['#006a4e', '#fff', '#e0293c', '#fff'],
  'egypt': ['#2f7d4f', '#fff', '#5a0f1b', '#f8f0e3'],
  'india': ['#1f7a4a', '#fff', '#0b1320', '#ffb200'],
  'indonesia': ['#2f8a5a', '#fff', '#1f3a5f', '#fff'],
  'nigeria': ['#008751', '#fff', '#111', '#ffcc00'],
  'pakistan': ['#3cc77e', '#0a241d', '#e7b54a', '#0a241d'],
  'united-kingdom': ['#2b7a52', '#fff', '#10263b', '#fff'],
  'united-states': ['#1f8a4c', '#fff', '#1d3d8f', '#fff'],
  // Topic guides
  'anonymous-chat': ['#2f6b3f', '#fff', '#b3261e', '#fff'],
  'country-chat-guide': ['#1f8a4c', '#fff', '#1a1a1a', '#f5f3ee'],
  'how-it-works': ['#3ddc84', '#06210f', '#ffd166', '#123a6b'],
  'language-chat-guide': ['#1f8a4c', '#fff', '#1f1b16', '#fbf7ef'],
  'language-exchange': ['#1d7a55', '#fff', '#f08a24', '#1d2423'],
  'late-night-chat': ['#4fd68b', '#07091a', '#9a8cf0', '#07091a'],
  'make-friends-online': ['#2f9a5a', '#fff', '#ef6a4c', '#fff'],
  'omegle-alternative': ['#1a7f4b', '#fff', '#1f6feb', '#fff'],
  'practice-english-speaking': ['#2e8b57', '#fff', '#1d4fbf', '#fff'],
  'random-call': ['#3f8a5a', '#fff', '#c8372d', '#fff'],
  'random-text-chat': ['#39ff88', '#0a0f0b', '#ffcf5c', '#0a0f0b'],
  'random-voice-chat': ['#3ee08f', '#0d1b2e', '#e8eef6', '#0d1b2e'],
  'resources': ['#3f7a4a', '#fff', '#6b4a2b', '#fff'],
  'safety': ['#0a7d4f', '#fff', '#14231c', '#fff'],
  'talk-to-someone': ['#3f8a5f', '#fff', '#6b4c7a', '#fff'],
  'talk-to-strangers': ['#c6f432', '#111', '#111', '#c6f432'],
  'voice-chat-vs-video-chat': ['#1f8a4c', '#fff', '#2457c5', '#fff'],
};

function ctaVars(slug) {
  const t = CTA_THEMES[slug];
  if (!t) return '';
  return `:root{--cta-talk:${t[0]};--cta-talk-ink:${t[1]};--cta-chat:${t[2]};--cta-chat-ink:${t[3]}}`;
}

// --- Start talking: the call-to-action component -----------------------------
// Links go straight into a match: /?talk=1 starts the voice flow and
// /chat?go=1 the text one, so the tap on this page is the only tap. They are
// nofollow because they are actions, not pages - every query-string variant of
// / that Google crawls is one more duplicate filed against the real homepage.
const PHONE_SVG = '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M6.62 10.79c1.44 2.83 3.76 5.14 6.59 6.59l2.2-2.2c.27-.27.67-.36 1.02-.24 1.12.37 2.33.57 3.57.57.55 0 1 .45 1 1V20c0 .55-.45 1-1 1-9.39 0-17-7.61-17-17 0-.55.45-1 1-1h3.5c.55 0 1 .45 1 1 0 1.25.2 2.45.57 3.57.11.35.03.74-.25 1.02l-2.2 2.2z"/></svg>';
const CHAT_SVG = '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M20 2H4c-1.1 0-2 .9-2 2v18l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zM7 9.5h10a1 1 0 1 1 0 2H7a1 1 0 1 1 0-2zm0-3.5h10a1 1 0 1 1 0 2H7a1 1 0 1 1 0-2zm0 7h6a1 1 0 1 1 0 2H7a1 1 0 1 1 0-2z"/></svg>';
const ARROW_SVG = '<svg class="tl-go-arr" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m9 6 6 6-6 6"/></svg>';

function ctaButtons(src, talk, chat) {
  const t = talk || {}, c = chat || {};
  return `<a class="tl-go-btn tl-go-talk" href="/?talk=1&amp;utm_source=${src}" rel="nofollow" data-tl-go="talk">${PHONE_SVG}<span class="tl-go-txt">${esc(t.label || 'Tap to Talk')}<small>${esc(t.sub || 'Live voice call · no camera')}</small></span>${ARROW_SVG}</a>`
    + `<a class="tl-go-btn tl-go-chat" href="/chat?go=1&amp;utm_source=${src}" rel="nofollow" data-tl-go="chat">${CHAT_SVG}<span class="tl-go-txt">${esc(c.label || 'Tap to Chat')}<small>${esc(c.sub || 'Text chat · no mic needed')}</small></span>${ARROW_SVG}</a>`;
}

// The block itself. `o.title` / `o.sub` are the page's own words for it;
// `o.src` the utm_source the server counts (blog | seo).
function ctaHero(o = {}) {
  return `<section class="tl-go${o.wide ? ' tl-go-wide' : ''}" aria-label="Start a conversation">
<h2 class="tl-go-h">${esc(o.title || 'Talk to someone right now')}</h2>
<p class="tl-go-sub">${esc(o.sub || 'One tap and you are matched with a real person, usually in seconds.')}</p>
<div class="tl-go-row">${ctaButtons(o.src || 'blog', o.talk, o.chat)}</div>
<p class="tl-go-fine">Free &middot; No sign-up &middot; No camera &middot; Adults 18+</p>
</section>`;
}

// Fixed bottom bar, shown by /cta.js once the page's own block has scrolled
// out of view, so a way in is always one thumb away while reading.
function ctaDock(src = 'blog') {
  return `<nav class="tl-dock" aria-label="Start a conversation" data-tl-dock>${ctaButtons(src)}</nav>
<script defer src="/cta.js?v=${CTA_JS_VERSION}"></script>`;
}

function moreStories(all, slug) {
  const self = all.findIndex(a => a.slug === slug);
  const picks = [1, 2, 3].map(k => all[(self + k) % all.length]);
  return `<aside class="j-more" aria-label="More from the Journal"><h2>More from the Journal</h2><ul>${picks.map(a =>
    `<li><a href="/blog/${a.slug}">${esc(a.h1)}</a></li>`).join('')}</ul></aside>`;
}

function page(p, inner) {
  return `${head(p)}
<body class="${p.bodyClass || ''}">
${masthead()}
${inner}
${footer()}
${ctaDock(p.ctaSrc || 'blog')}
</body>
</html>
`;
}

function write(rel, html) {
  const file = path.join(PUBLIC, rel);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, html);
}

module.exports = { SITE, PUBLIC, CSS_VERSION, ctaVars, CTA_THEMES, esc, words, page, ad, moreStories, write, journalCss, ctaHero, ctaDock, ctaButtons };
