'use strict';
/*
 * Shared plumbing for the TalkLive Journal: the ten long-form articles under
 * /blog/, the journal front page, and the /languages/ feature.
 *
 * Every page here is hand-designed. Each article brings its own typography and
 * layout (its `css`); this file only supplies what has to be identical on all
 * of them - the <head> metadata, a quiet masthead, the legal footer, one ad
 * slot, and the @font-face rules for the self-hosted fonts in
 * public/fonts/mag/ (the site CSP allows fonts from 'self' only, so Google
 * Fonts cannot be used).
 *
 * The pages deliberately carry no "Talk now" buttons. They are reading pages.
 */
const fs = require('fs');
const path = require('path');

const SITE = 'https://talklive.app';
const PUBLIC = path.join(__dirname, '..', '..', 'public');
const OG_IMAGE = `${SITE}/og-image.png?v=2`;
const CSS_VERSION = '20261005countries';

// family -> [ [weight, style, file] ]
const FONTS = {
  'Abril Fatface': [[400, 'normal', 'abril-fatface-latin-400-normal']],
  'Anton': [[400, 'normal', 'anton-latin-400-normal']],
  'Bebas Neue': [[400, 'normal', 'bebas-neue-latin-400-normal']],
  'Big Shoulders Display': [[600, 'normal', 'big-shoulders-display-latin-600-normal'], [800, 'normal', 'big-shoulders-display-latin-800-normal']],
  'Bricolage Grotesque': [[400, 'normal', 'bricolage-grotesque-latin-400-normal'], [700, 'normal', 'bricolage-grotesque-latin-700-normal']],
  'Courier Prime': [[400, 'normal', 'courier-prime-latin-400-normal'], [700, 'normal', 'courier-prime-latin-700-normal']],
  'Instrument Serif': [[400, 'normal', 'instrument-serif-latin-400-normal'], [400, 'italic', 'instrument-serif-latin-400-italic']],
  'Nunito': [[400, 'normal', 'nunito-latin-400-normal'], [800, 'normal', 'nunito-latin-800-normal']],
  'Manrope': [[400, 'normal', 'manrope-latin-400-normal'], [700, 'normal', 'manrope-latin-700-normal']],
  'Syne': [[800, 'normal', 'syne-latin-800-normal']],
  'Unbounded': [[500, 'normal', 'unbounded-latin-500-normal'], [800, 'normal', 'unbounded-latin-800-normal']],
  'Archivo Black': [[400, 'normal', 'archivo-black-latin-400-normal']],
  'Archivo': [[400, 'normal', 'archivo-latin-400-normal'], [600, 'normal', 'archivo-latin-600-normal']],
  'Caveat': [[500, 'normal', 'caveat-latin-500-normal']],
  'Cormorant Garamond': [[500, 'normal', 'cormorant-garamond-latin-500-normal'], [500, 'italic', 'cormorant-garamond-latin-500-italic'], [700, 'normal', 'cormorant-garamond-latin-700-normal']],
  'DM Sans': [[400, 'normal', 'dm-sans-latin-400-normal'], [500, 'normal', 'dm-sans-latin-500-normal']],
  'DM Serif Display': [[400, 'normal', 'dm-serif-display-latin-400-normal'], [400, 'italic', 'dm-serif-display-latin-400-italic']],
  'Fraunces': [[400, 'normal', 'fraunces-latin-400-normal'], [400, 'italic', 'fraunces-latin-400-italic'], [700, 'normal', 'fraunces-latin-700-normal']],
  'IBM Plex Sans': [[500, 'normal', 'ibm-plex-sans-latin-500-normal']],
  'IBM Plex Serif': [[400, 'normal', 'ibm-plex-serif-latin-400-normal'], [400, 'italic', 'ibm-plex-serif-latin-400-italic'], [600, 'normal', 'ibm-plex-serif-latin-600-normal']],
  'Inter': [[400, 'normal', 'inter-latin-400-normal'], [600, 'normal', 'inter-latin-600-normal']],
  'JetBrains Mono': [[400, 'normal', 'jetbrains-mono-latin-400-normal']],
  'Libre Caslon Text': [[400, 'normal', 'libre-caslon-text-latin-400-normal'], [400, 'italic', 'libre-caslon-text-latin-400-italic'], [700, 'normal', 'libre-caslon-text-latin-700-normal']],
  'Literata': [[400, 'normal', 'literata-latin-400-normal'], [400, 'italic', 'literata-latin-400-italic'], [700, 'normal', 'literata-latin-700-normal']],
  'Lora': [[400, 'normal', 'lora-latin-400-normal'], [400, 'italic', 'lora-latin-400-italic'], [700, 'normal', 'lora-latin-700-normal']],
  'Old Standard TT': [[700, 'normal', 'old-standard-tt-latin-700-normal']],
  'Playfair Display': [[700, 'normal', 'playfair-display-latin-700-normal'], [400, 'italic', 'playfair-display-latin-400-italic']],
  'Source Serif 4': [[400, 'normal', 'source-serif-4-latin-400-normal'], [400, 'italic', 'source-serif-4-latin-400-italic'], [600, 'normal', 'source-serif-4-latin-600-normal']],
  'Space Grotesk': [[400, 'normal', 'space-grotesk-latin-400-normal'], [700, 'normal', 'space-grotesk-latin-700-normal']],
};

function journalCss() {
  const faces = Object.entries(FONTS).flatMap(([family, list]) => list.map(([w, s, file]) =>
    `@font-face{font-family:"${family}";font-style:${s};font-weight:${w};font-display:swap;src:url(/fonts/mag/${file}.woff2) format("woff2")}`));
  return `/* TalkLive Journal - generated by scripts/journal/shared.js. Do not edit. */
${faces.join('\n')}
*,*::before,*::after{box-sizing:border-box}
html{-webkit-text-size-adjust:100%;text-size-adjust:100%}
body{margin:0;background:var(--paper,#fff);color:var(--ink,#111);text-rendering:optimizeLegibility;-webkit-font-smoothing:antialiased}
img,svg{max-width:100%;height:auto}
a{color:inherit}
.skip{position:absolute;left:-9999px}.skip:focus{left:12px;top:12px;background:#fff;color:#000;padding:8px 12px;z-index:9}
.j-mast{display:flex;align-items:center;justify-content:space-between;gap:16px;max-width:1120px;margin:0 auto;padding:14px 20px;font:500 13px/1.2 system-ui,-apple-system,"Segoe UI",sans-serif;letter-spacing:.04em;color:var(--mast,currentColor);border-bottom:1px solid var(--rule,rgba(0,0,0,.12))}
.j-mast a{text-decoration:none}
.j-mast .j-brand{font-weight:600;text-transform:uppercase;letter-spacing:.14em;white-space:nowrap}
.j-mast nav{display:flex;gap:18px;flex-wrap:wrap}
.j-mast nav a{opacity:.75}.j-mast nav a:hover{opacity:1;text-decoration:underline}
.j-foot{max-width:1120px;margin:72px auto 0;padding:28px 20px 40px;border-top:1px solid var(--rule,rgba(0,0,0,.12));font:400 13px/1.7 system-ui,-apple-system,"Segoe UI",sans-serif;color:var(--mast,currentColor)}
.j-foot nav{display:flex;flex-wrap:wrap;gap:6px 18px;margin-bottom:10px}
.j-foot a{opacity:.8}
.j-foot p{margin:0;opacity:.6}
.j-more{max-width:1120px;margin:64px auto 0;padding:0 20px}
.j-more h2{font:600 12px/1 system-ui,-apple-system,"Segoe UI",sans-serif;letter-spacing:.16em;text-transform:uppercase;margin:0 0 14px;opacity:.7}
.j-more ul{list-style:none;margin:0;padding:0;display:grid;gap:12px;grid-template-columns:repeat(auto-fit,minmax(220px,1fr))}
.j-more li{border-top:1px solid var(--rule,rgba(0,0,0,.12));padding-top:10px}
.j-more a{text-decoration:none;font:inherit}
.j-more a:hover{text-decoration:underline}
.ad-card{max-width:728px;margin:48px auto;padding:10px 0 0;border-top:1px solid var(--rule,rgba(0,0,0,.12));text-align:center}
.ad-card-label{display:block;font:500 10px/1 system-ui,-apple-system,"Segoe UI",sans-serif;letter-spacing:.18em;text-transform:uppercase;opacity:.5;margin-bottom:8px}
@media (max-width:640px){.j-mast{flex-wrap:wrap;gap:8px 14px;font-size:12px}.j-mast nav{gap:14px}}
`;
}

function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function words(html) {
  return html.replace(/<style[\s\S]*?<\/style>/g, '').replace(/<[^>]+>/g, ' ').split(/\s+/).filter(Boolean).length;
}

// Preload only the faces the page leads with, so the headline does not swap.
function preloads(files) {
  return (files || []).map(f => `<link rel="preload" href="/fonts/mag/${f}.woff2" as="font" type="font/woff2" crossorigin />`).join('\n');
}

function head(p) {
  const canonical = `${SITE}${p.path}`;
  const ld = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'Organization', '@id': `${SITE}/#organization`, name: 'TalkLive', url: `${SITE}/`,
        logo: { '@type': 'ImageObject', url: `${SITE}/favicon-192.png`, width: 192, height: 192 },
      },
      p.article ? {
        '@type': 'Article', '@id': `${canonical}#article`, headline: p.h1, description: p.description,
        datePublished: p.date, dateModified: p.updated || p.date, inLanguage: 'en',
        mainEntityOfPage: canonical, image: OG_IMAGE, wordCount: p.wordCount,
        author: { '@type': 'Organization', name: 'TalkLive Journal', url: `${SITE}/blog/` },
        publisher: { '@id': `${SITE}/#organization` },
        articleSection: p.tag,
      } : {
        '@type': 'CollectionPage', '@id': `${canonical}#webpage`, name: p.title, description: p.description, url: canonical,
        publisher: { '@id': `${SITE}/#organization` },
      },
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Home', item: `${SITE}/` },
          { '@type': 'ListItem', position: 2, name: 'Journal', item: `${SITE}/blog/` },
        ].concat(p.path === '/blog/' ? [] : [{ '@type': 'ListItem', position: 3, name: p.crumb || p.h1, item: canonical }]),
      },
    ],
  };
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
<title>${esc(p.title)}</title>
<meta name="description" content="${esc(p.description)}" />
<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1" />
<meta name="theme-color" content="${p.theme || '#ffffff'}" />
<meta name="author" content="TalkLive Journal" />
<link rel="canonical" href="${canonical}" />
<link rel="alternate" type="application/rss+xml" title="TalkLive Journal" href="${SITE}/blog/feed.xml" />
<meta property="og:type" content="${p.article ? 'article' : 'website'}" />
<meta property="og:site_name" content="TalkLive" />
<meta property="og:title" content="${esc(p.h1)}" />
<meta property="og:description" content="${esc(p.description)}" />
<meta property="og:url" content="${canonical}" />
<meta property="og:image" content="${OG_IMAGE}" />
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="630" />
<meta property="og:image:alt" content="${esc(p.h1)} - TalkLive Journal" />
<meta property="og:locale" content="en_US" />
${p.article ? `<meta property="article:published_time" content="${p.date}" />
<meta property="article:modified_time" content="${p.updated || p.date}" />
<meta property="article:section" content="${esc(p.tag)}" />
` : ''}<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="${esc(p.h1)}" />
<meta name="twitter:description" content="${esc(p.description)}" />
<meta name="twitter:image" content="${OG_IMAGE}" />
<meta name="twitter:image:alt" content="${esc(p.h1)} - TalkLive Journal" />
<link rel="icon" href="/favicon.svg" type="image/svg+xml" />
<link rel="apple-touch-icon" href="/favicon-192.png" />
<link rel="manifest" href="/site.webmanifest" />
${preloads(p.preload)}
<link rel="stylesheet" href="/journal.css?v=${CSS_VERSION}" />
<style>${p.css}</style>
<script defer src="/pwa.js?v=20260908pwa"></script>
<script type="application/ld+json">${JSON.stringify(ld)}</script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5162304231095978"
     crossorigin="anonymous"></script>
<script defer src="/ads.js?v=20260923adsense2"></script>
</head>`;
}

function masthead() {
  return `<a class="skip" href="#story">Skip to the article</a>
<header class="j-mast">
  <a class="j-brand" href="/blog/">TalkLive Journal</a>
  <nav aria-label="Journal"><a href="/blog/">All stories</a><a href="/languages/">Languages</a><a href="/about">About</a><a href="/">TalkLive</a></nav>
</header>`;
}

function footer() {
  return `<footer class="j-foot">
  <nav aria-label="Site"><a href="/about">About</a><a href="/contact">Contact</a><a href="/privacy">Privacy Policy</a><a href="/terms">Terms</a><a href="/community-guidelines">Community Guidelines</a><a href="/safety">Safety</a><a href="/">TalkLive home</a></nav>
  <p>&copy; ${new Date().getFullYear()} TalkLive. The Journal is written by the TalkLive team. Corrections: info@talklive.app</p>
</footer>`;
}

function ad() {
  return `<div class="ad-card"><span class="ad-card-label">Advertisement</span><div data-ad="native"></div></div>`;
}

function moreStories(all, slug) {
  const self = all.findIndex(a => a.slug === slug);
  const picks = [1, 2, 3].map(k => all[(self + k) % all.length]);
  return `<aside class="j-more" aria-label="More from the Journal"><h2>More from the Journal</h2><ul>${picks.map(a =>
    `<li><a href="/blog/${a.slug}">${esc(a.h1)}</a></li>`).join('')}</ul></aside>`;
}

function page(p, inner) {
  return `${head(p)}
<body class="${p.bodyClass || ''}">
${masthead()}
${inner}
${footer()}
</body>
</html>
`;
}

function write(rel, html) {
  const file = path.join(PUBLIC, rel);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, html);
}

module.exports = { SITE, PUBLIC, esc, words, page, ad, moreStories, write, journalCss };
