'use strict';

/*
 * Search and navigation hubs for TalkLive.
 *
 * These objects use the same shape as the landing-page entries consumed by
 * scripts/build-seo.js. They are intentionally written as useful directories
 * rather than thin keyword variants: each hub owns one search intent, links
 * to the most relevant existing material, and states product/privacy limits
 * plainly.
 */

module.exports = [
  {
    slug: 'resources',
    crumb: 'Resources',
    eyebrow: 'Guides and practical help',
    title: 'TalkLive Resources - Voice Chat, Safety & Conversation Guides',
    description: 'Explore practical TalkLive resources for safer stranger chat, better conversations, language practice, privacy, country preferences and choosing the right chat format.',
    keywords: 'voice chat resources, stranger chat guides, conversation guides, random chat help, online chat safety resources, language practice guides',
    h1: 'Resources for Better, Safer Conversations',
    lede: 'Start with the question you actually have: how TalkLive works, how to protect your privacy, what to say after hello, how to practise a language, or whether voice chat is the right format for you.',
    cta: 'Start a Voice Chat',
    ctaChat: 'Start a Text Chat',
    featuresH: 'Find the right starting point',
    featuresIntro: 'Each section has a clear job, so you can get an answer without searching through a wall of loosely related articles.',
    features: [
      { icon: 'shield', h: 'Safety and privacy', p: 'Learn what TalkLive can protect, what another participant can still do, and when to leave or report a conversation.' },
      { icon: 'mic', h: 'Voice-chat basics', p: 'Understand microphone permissions, matching, encrypted WebRTC connections and TalkLive\'s production TURN relay.' },
      { icon: 'chat', h: 'Conversation skills', p: 'Use practical openers, follow-up questions and polite exits without turning a spontaneous call into a script.' },
      { icon: 'globe', h: 'Languages and practice', p: 'Choose a translated interface and use real conversations as practice without assuming every match is a tutor or native speaker.' },
      { icon: 'users', h: 'Formats and alternatives', p: 'Compare voice, text, video and room-based chat by exposure, bandwidth, pace and the kind of interaction each supports.' },
      { icon: 'world', h: 'Country discovery', p: 'Learn how country preferences work and why availability, time zones and the live queue mean no country match is guaranteed.' },
    ],
    stepsH: 'How to use the resource library',
    stepsIntro: 'A useful guide should help you make one decision or take one safer action.',
    steps: [
      { h: 'Choose your goal', p: 'Pick safety, product help, language practice, conversation skills, comparisons or country discovery.' },
      { h: 'Read the focused guide', p: 'Start with the hub summary, then follow only the contextual links that answer your next question.' },
      { h: 'Set your boundaries', p: 'Decide what you will not share, how long you want to chat and what behaviour will make you leave.' },
      { h: 'Try a conversation', p: 'Choose voice or text, keep expectations realistic, and use Next, block or report whenever you need to.' },
    ],
    prose: [
      { h: 'Start with the kind of help you need', body: [
        `For privacy controls, recording limits and reporting guidance, begin at the <a href="/safety">Safety Center</a>. For a plain-language explanation of matching, signalling, encrypted WebRTC audio and TalkLive's production TURN relay, read <a href="/how-it-works">How TalkLive Works</a>. Those two hubs explain the product before asking you to trust it.`,
        `If your goal is discovery, use the <a href="/languages">Languages hub</a> for translated interfaces and speaking-practice guidance, the <a href="/countries">Countries hub</a> for honest information about country preferences, or the <a href="/alternatives">Alternatives guide</a> to compare chat formats without pretending every service is interchangeable.`,
      ]},
      { h: 'Prepare for the conversation, not a performance', body: [
        `The <a href="/blog/how-to-start-a-conversation-with-a-stranger">conversation opener guide</a> is useful when the first ten seconds feel awkward. The <a href="/blog/how-to-end-a-conversation-politely">polite exit guide</a> is just as important: a short, clear goodbye is better than staying in a conversation neither person wants.`,
        `Language learners can pair the <a href="/practice-english-speaking">English speaking page</a> with the <a href="/blog/practice-english-speaking-online-free">practice routine</a>. A random match is practice with a real person, not a lesson: fluency, patience and willingness to correct you will vary.`,
      ]},
      { h: 'Use factual product information', body: [
        `TalkLive does not record or store voice audio. WebRTC encrypts audio in transit, and TalkLive uses a TURN relay in production for connectivity. Typed messages, reports and related operational data may be retained for a limited period as described in the <a href="/privacy">Privacy Policy</a>.`,
        `No guide can make stranger chat risk-free or guarantee that a particular person, country or language will be available. Country settings are matching preferences, not reservations. If a filtered match is unavailable, results may broaden according to the product's matching behaviour.`,
      ]},
      { h: 'A library that grows by usefulness', body: [
        `New resources should answer a distinct question, cite reliable sources when they make factual claims, and link to the feature or policy they describe. Broad claims about wellbeing, safety, competitors or user activity do not belong here without evidence.`,
        `For current long-form guides, browse the <a href="/blog/">TalkLive blog</a>. For billing limits and the exact difference between free and optional paid features, use the <a href="/pricing">Pricing page</a> rather than relying on a general article.`,
      ]},
    ],
    faq: [
      { q: 'Are these resources only for voice chat?', a: 'No. The library covers TalkLive voice and text modes, privacy, safety, language practice, country preferences and comparisons with other chat formats.' },
      { q: 'Does following the safety guidance make stranger chat risk-free?', a: 'No. It lowers avoidable risk, but another participant still controls their own device and behaviour. Leave, block or report whenever a conversation feels unsafe.' },
      { q: 'Can a guide guarantee a match from a country I choose?', a: 'No. Country preferences can narrow a search, but live availability changes and a specific country match is never guaranteed.' },
      { q: 'Are the wellbeing articles medical advice?', a: 'No. TalkLive is a social conversation service, not healthcare, counselling or a crisis service. Seek qualified local help for medical or urgent support needs.' },
      { q: 'Where should I check current pricing and limits?', a: 'Use the TalkLive Pricing page. It is the source of truth for free-tier limits, optional Premium features, billing, cancellation and refunds.' },
      { q: 'How can I suggest a correction?', a: 'Use the Contact page and include the URL, the statement that needs attention and a reliable source when relevant.' },
    ],
    ctaBandH: 'Ready to put the guides into practice?',
    ctaBandP: 'Choose voice or text, protect your boundaries, and start with a simple hello.',
    cluster: 'resources',
    primaryIntent: 'voice chat resources and stranger chat guides',
    relatedPages: ['safety', 'how-it-works', 'alternatives', 'languages', 'countries', 'pricing'],
    updated: '2026-08-14',
    posts: ['random-chat-safety-tips', 'how-to-start-a-conversation-with-a-stranger', 'how-to-end-a-conversation-politely'],
  },

  {
    slug: 'safety',
    crumb: 'Safety Center',
    eyebrow: 'Privacy, boundaries and control',
    title: 'TalkLive Safety Center - Privacy, Reporting & Stranger Chat Guidance',
    description: 'Understand TalkLive voice privacy, encrypted WebRTC and TURN relay use, text retention, reporting, blocking, identity boundaries and practical stranger-chat safety.',
    keywords: 'TalkLive safety, stranger chat safety, anonymous voice chat privacy, random chat safety, report and block, WebRTC voice privacy',
    h1: 'TalkLive Safety Center',
    lede: 'Stranger chat is never risk-free. This center explains the controls TalkLive provides, the limits technology cannot remove, and the habits that keep you in charge of every conversation.',
    cta: 'Talk with Safety Controls',
    ctaChat: 'Start a Text Chat',
    featuresH: 'What safety means on TalkLive',
    featuresIntro: 'Useful safety information separates platform controls from choices only you can make.',
    features: [
      { icon: 'mic', h: 'Voice is not recorded', p: 'TalkLive does not record or store voice audio. WebRTC encrypts it in transit through the production TURN relay.' },
      { icon: 'chat', h: 'Text may be retained', p: 'Typed messages, reports and related context may be kept for a limited period for delivery, safety and moderation as described in the Privacy Policy.' },
      { icon: 'next', h: 'Leave immediately', p: 'You do not owe a stranger an explanation. End the conversation or choose Next as soon as you feel uncomfortable.' },
      { icon: 'shield', h: 'Report and block', p: 'Reporting or blocking ends unwanted contact and gives the platform a signal it can use against repeated abuse.' },
      { icon: 'lock', h: 'Share less by default', p: 'Keep real names, exact location, workplace, school, financial details, passwords and private contact information out of stranger chat.' },
      { icon: 'users', h: 'Adults only', p: 'TalkLive is restricted to people aged 18 or older. An age rule does not replace caution or identity verification.' },
    ],
    stepsH: 'A safer routine for every match',
    stepsIntro: 'Make the decision to protect your information before a conversation gets interesting.',
    steps: [
      { h: 'Set a privacy boundary', p: 'Decide in advance which personal details, links, images, payments and off-platform accounts you will not share.' },
      { h: 'Start with low-stakes topics', p: 'Use general interests and broad locations rather than information that can identify your home, work or routine.' },
      { h: 'Notice pressure early', p: 'Requests for money, secrets, urgent links, explicit content or a quick move to another app are reasons to leave.' },
      { h: 'End, block or report', p: 'Use the control that fits the situation. For immediate danger or crime, contact the appropriate local authority.' },
    ],
    prose: [
      { h: 'No stranger-chat service can promise complete safety', body: [
        `TalkLive reduces some forms of exposure by offering voice and text without requiring video. That does not verify the identity, intentions or truthfulness of the person on the other side. Read the <a href="/blog/random-chat-safety-tips">practical safety rules</a> before your first match and treat pressure as useful information, not something you have to negotiate with.`,
        `The fastest safety control is leaving. Next, block and report exist so you can act without debating whether someone has crossed a precise line. The <a href="/terms">Terms</a> explain prohibited behaviour; they do not require you to stay until a violation is proven.`,
      ]},
      { h: 'What happens to voice and text', body: [
        `TalkLive does not record or store voice audio. As explained in <a href="/how-it-works">How TalkLive Works</a>, WebRTC encrypts audio in transit and TalkLive uses a TURN relay in production for connectivity. Relaying encrypted packets is not the same as creating an audio recording.`,
        `Typed chat is different. Messages, reports and supporting operational information may be retained for a limited, rolling period so the service can deliver features and respond to misuse. The current details and retention wording live in the <a href="/privacy">Privacy Policy</a>, which should be treated as the source of truth.`,
      ]},
      { h: 'The other participant controls their device', body: [
        `A person who can hear a call can use device software or another physical device to record it. No browser protocol can prevent an endpoint from capturing sound after it has been decrypted for playback. Speak as though the other participant could keep what you say, even though TalkLive itself does not record the call.`,
        `Do not share authentication codes, recovery phrases, banking details, identity documents or intimate material. Avoid links sent by strangers; if a conversation becomes a request for money, investment, emergency assistance or account access, leave and report it.`,
      ]},
      { h: 'Country preferences are not identity checks', body: [
        `A country label or matching preference is not proof of nationality, residence, language or location. Availability changes with the live queue, and choosing a country does not guarantee that a match from that country will be available. Learn more in the <a href="/countries">Countries hub</a>.`,
        `TalkLive is not a crisis line, counselling service or emergency service. If you or another person may be in immediate danger, contact local emergency services or a qualified crisis resource in the relevant country rather than relying on a random match.`,
      ]},
    ],
    faq: [
      { q: 'Is TalkLive completely safe?', a: 'No stranger-chat service can guarantee that. TalkLive provides privacy, exit, block and report controls, while users still need to protect personal information and leave unsafe conversations.' },
      { q: 'Does TalkLive record voice calls?', a: 'No. TalkLive does not record or store voice audio. WebRTC encrypts the connection and uses a TURN relay in production.' },
      { q: 'Could the other person record me?', a: 'Yes. Any call participant can potentially record sound on their own device or with another device. Do not say anything you would be harmed by having saved or shared.' },
      { q: 'Are text messages saved?', a: 'Typed messages, reports and related context may be retained for a limited period for delivery, moderation and safety. See the current Privacy Policy for details.' },
      { q: 'What does reporting do?', a: 'It ends the unwanted interaction and supplies a moderation signal. Reports should be accurate; immediate danger or suspected crime should also be taken to the relevant local authority.' },
      { q: 'Does a country filter verify someone\'s location?', a: 'No. A filter is a matching preference, not identity or residence verification, and a specific country match is not guaranteed.' },
    ],
    ctaBandH: 'Stay in control from the first hello',
    ctaBandP: 'Share less, trust pressure signals, and leave or report the moment a conversation stops feeling right.',
    cluster: 'trust-and-safety',
    primaryIntent: 'TalkLive safety and anonymous stranger chat privacy',
    relatedPages: ['how-it-works', 'privacy', 'terms', 'countries', 'resources'],
    updated: '2026-08-14',
    posts: ['random-chat-safety-tips', 'is-talklive-safe', 'how-anonymous-voice-chat-works'],
  },

  {
    slug: 'alternatives',
    crumb: 'Chat Alternatives',
    eyebrow: 'Compare by fit, not hype',
    title: 'Random Chat Alternatives - Compare Voice, Text, Video & Rooms',
    description: 'Compare random voice chat, text chat, video roulette, public rooms and app-based alternatives by privacy, bandwidth, pace, controls, cost and the experience you want.',
    keywords: 'random chat alternatives, Omegle alternatives, voice chat vs video chat, stranger chat comparison, anonymous chat alternatives, chat apps compared',
    h1: 'Choose the Random Chat Format That Fits You',
    lede: 'The best alternative depends on what you want to expose, whether you can speak aloud, how much bandwidth you have, and whether you want a conversation, a room or a camera-first experience.',
    cta: 'Try Voice Chat',
    ctaChat: 'Try Text Chat',
    featuresH: 'Start with the meaningful differences',
    featuresIntro: 'Product names change; these format-level trade-offs stay useful.',
    features: [
      { icon: 'mic', h: 'Voice-first chat', p: 'Carries tone and personality without requiring a camera, but your voice itself is still personal information.' },
      { icon: 'chat', h: 'Text-first chat', p: 'Works silently and with minimal bandwidth, while making identity and intent harder to judge.' },
      { icon: 'users', h: 'Video roulette', p: 'Provides visual presence immediately, with greater exposure, bandwidth use and recording risk.' },
      { icon: 'world', h: 'Public rooms', p: 'Support group conversation and passive listening, but can make one-to-one depth and moderation harder.' },
      { icon: 'bolt', h: 'Browser or installed app', p: 'A browser reduces installation friction; an installed app may offer deeper device integration and persistent permissions.' },
      { icon: 'shield', h: 'Controls and policies', p: 'Compare exit, block, report, age, retention and pricing policies before trusting a logo or a ranking.' },
    ],
    stepsH: 'How to compare chat services honestly',
    stepsIntro: 'Choose for your actual use case rather than chasing one universal winner.',
    steps: [
      { h: 'Pick the medium', p: 'Decide whether you want voice, text, video, a group room or a combination before comparing brands.' },
      { h: 'Check what you expose', p: 'Review camera, microphone, account, profile, location and contact-information requirements.' },
      { h: 'Read the current limits', p: 'Confirm free-tier caps, filters, subscriptions, retention and moderation from first-party pages.' },
      { h: 'Try a short session', p: 'Test connection quality, exit controls and the live queue without sharing identifying details.' },
    ],
    prose: [
      { h: 'What TalkLive is - and is not', body: [
        `TalkLive is a browser-based random voice and text service for adults. It does not provide random video calls or public multi-person rooms. If seeing the other participant or joining a large group is your main goal, another format is the better fit. The <a href="/blog/voice-chat-vs-video-chat">voice-versus-video guide</a> explains the exposure and bandwidth trade-off in more detail.`,
        `Voice mode asks for microphone permission; text mode does not need a microphone. TalkLive does not record voice calls, although another participant may record on their own device. Typed messages and report context may be retained as explained in the <a href="/privacy">Privacy Policy</a>.`,
      ]},
      { h: 'Use competitor pages as fit guides', body: [
        `People arriving from Omegle-style products can start with the <a href="/omegle-alternative">Omegle alternative guide</a>. There are also focused pages for people comparing <a href="/ometv-alternative">OmeTV and TalkLive</a> or <a href="/chatroulette-alternative">Chatroulette and TalkLive</a>. These pages should be read as format comparisons, not promises that TalkLive reproduces every competitor feature.`,
        `Features and prices change. Before making a decision, verify a competitor's current details on its official pages and verify TalkLive limits on <a href="/pricing">Pricing</a>. A useful comparison says who should not choose TalkLive as clearly as who may prefer it.`,
      ]},
      { h: 'A practical format checklist', body: [
        `Choose voice when you want a real-time conversation without video and can speak aloud. Choose text when you need silence, lower commitment or minimal data use. Choose video only when visual presence is worth the added exposure. Choose a room when listening to or joining a group matters more than guaranteed one-to-one airtime.`,
        `Then check the operational details: whether an account is required, whether conversations are retained, how reports work, what is paid, whether the service is age-restricted, and how quickly you can leave. The <a href="/safety">Safety Center</a> provides the TalkLive side of that checklist.`,
      ]},
      { h: 'Filters guide a queue; they do not reserve a person', body: [
        `TalkLive offers optional country and interest preferences. They can narrow a search but cannot guarantee a person from a particular country, with a particular identity or speaking a particular language. Availability changes from moment to moment, and matching may broaden when a preferred match is unavailable.`,
        `If country discovery is your main goal, read the <a href="/countries">Countries hub</a>. If speaking practice is the goal, use the <a href="/languages">Languages hub</a> and begin each call by confirming which language both people want to use.`,
      ]},
    ],
    faq: [
      { q: 'Is TalkLive a video-chat alternative?', a: 'It is an alternative for people who want random conversation without video. TalkLive does not offer random video calls, so it is not a feature-for-feature video replacement.' },
      { q: 'Is voice safer than video?', a: 'Voice avoids exposing your face and surroundings, but it is not risk-free. Your voice can identify you, another participant may record, and normal stranger-chat precautions still apply.' },
      { q: 'Do I need an account to try TalkLive?', a: 'No account is required for a basic random voice or text match. Optional account and paid features should be checked on the current Pricing page.' },
      { q: 'Can I choose an exact country or language?', a: 'You can set preferences, but a specific country, language, identity or level of fluency is not guaranteed. Live availability determines who can be matched.' },
      { q: 'Which format uses the least data?', a: 'Text generally uses the least data, voice uses more, and video usually uses substantially more. Actual usage varies by session and network.' },
      { q: 'How current are competitor comparisons?', a: 'Competitor features can change without notice. Check the reviewed date on a comparison and confirm important details using the competitor\'s official information.' },
    ],
    ctaBandH: 'Want conversation without turning on a camera?',
    ctaBandP: 'Try one short voice or text match and decide from the experience, not a ranking.',
    cluster: 'comparisons',
    primaryIntent: 'random chat alternatives and voice versus video chat comparison',
    relatedPages: ['omegle-alternative', 'ometv-alternative', 'chatroulette-alternative', 'safety', 'languages', 'countries'],
    updated: '2026-08-14',
    posts: ['best-random-chat-apps-2026', 'voice-chat-vs-video-chat', 'best-omegle-alternatives'],
  },

  {
    slug: 'languages',
    crumb: 'Languages',
    eyebrow: 'Translated interfaces and speaking practice',
    title: 'TalkLive Languages - Localized Chat Pages & Speaking Practice',
    description: 'Open TalkLive in a supported language, practise real conversation responsibly, understand matching limits and find language-learning guides for anonymous voice or text chat.',
    keywords: 'language voice chat, speaking practice online, multilingual chat, language exchange voice, practice languages with strangers, localized random chat',
    h1: 'TalkLive in Your Language',
    lede: 'Use a translated TalkLive interface, practise speaking with real people, or meet someone outside your usual language circle - with clear expectations about what random matching can and cannot promise.',
    cta: 'Start Speaking',
    ctaChat: 'Start Text Practice',
    featuresH: 'Language tools without false guarantees',
    featuresIntro: 'A translated interface makes the product easier to use; it does not certify the language or fluency of a random participant.',
    features: [
      { icon: 'world', h: 'Localized entry pages', p: 'Open a statically translated homepage in one of the supported interface languages before entering the app.' },
      { icon: 'mic', h: 'Real-time speaking', p: 'Practise listening, pronunciation and spontaneous answers with a person rather than a prerecorded exercise.' },
      { icon: 'chat', h: 'Silent text option', p: 'Use text when you cannot speak aloud or want time to assemble a sentence before sending it.' },
      { icon: 'globe', h: 'Optional country preferences', p: 'Country settings can steer matching, but they do not guarantee a country, language, nationality or native speaker.' },
      { icon: 'heart', h: 'Low-stakes repetition', p: 'Keep sessions short, ask whether correction is welcome and leave respectfully when the language goals do not align.' },
      { icon: 'shield', h: 'The same safety rules', p: 'Language practice does not require a real name, exact location, school, workplace, private account or payment.' },
    ],
    stepsH: 'How to use TalkLive for language practice',
    stepsIntro: 'Make your goal clear, keep it mutual and treat every match as a person rather than a free lesson.',
    steps: [
      { h: 'Choose the interface', p: 'Open the localized page that makes controls and safety information easiest for you to understand.' },
      { h: 'Choose voice or text', p: 'Use voice for spontaneous speech and listening, or text for written practice and quieter situations.' },
      { h: 'Confirm the language', p: 'Ask which language both people want to use and whether either person wants corrections.' },
      { h: 'Practise, thank and move on', p: 'Focus on one useful goal, avoid turning the call into an interrogation, and end courteously.' },
    ],
    prose: [
      { h: 'Supported localized entry pages', body: [
        `TalkLive currently provides localized homepages for <a href="/es/">Español</a>, <a href="/pt/">Português</a>, <a href="/fr/">Français</a>, <a href="/de/">Deutsch</a>, <a href="/it/">Italiano</a>, <a href="/ru/">Русский</a>, <a href="/tr/">Türkçe</a> and <a href="/id/">Bahasa Indonesia</a>.`,
        `Additional entry pages are available in <a href="/ar/">العربية</a>, <a href="/fa/">فارسی</a>, <a href="/hi/">हिन्दी</a>, <a href="/ur/">اردو</a>, <a href="/bn/">বাংলা</a>, <a href="/zh/">中文</a>, <a href="/ja/">日本語</a> and <a href="/ko/">한국어</a>. The legal policies remain the source of truth if a translated summary and an English policy ever differ.`,
      ]},
      { h: 'Interface language is not match language', body: [
        `Choosing a translated page changes how TalkLive is presented to you. It does not place you in a certified language classroom or guarantee that the next person speaks that language. Country preferences are also not language filters: countries are multilingual, location labels are not identity proof, and a preferred-country match may not be available.`,
        `Start each session with a simple agreement: which language, how long, and whether corrections are welcome. If the match is not suitable, use Next without blaming the other person; they joined for their own conversation goal too.`,
      ]},
      { h: 'Build a repeatable practice habit', body: [
        `For English, begin with <a href="/practice-english-speaking">Practice English Speaking</a> and the <a href="/blog/practice-english-speaking-online-free">30-day speaking routine</a>. The broader <a href="/language-exchange">Language Exchange guide</a> explains how to make the practice mutual rather than treating a stranger as an unpaid tutor.`,
        `A useful session can be five minutes: introduce yourself without identifying details, ask two open questions, notice one phrase you want to reuse, and finish with a clear thank-you. Consistency matters more than forcing every random match into a long lesson.`,
      ]},
      { h: 'Practise safely across languages', body: [
        `Misunderstandings happen more easily across language levels, so clarify rather than escalating. At the same time, language difficulty is not a reason to ignore pressure for money, private photos, verification codes, exact location or off-platform contact. The <a href="/safety">Safety Center</a> applies in every language.`,
        `Translation feedback is welcome through <a href="/contact">Contact</a>. Include the page, the current wording, the suggested wording and the dialect or regional context so a correction can be reviewed accurately.`,
      ]},
    ],
    faq: [
      { q: 'Does TalkLive match me by language?', a: 'Not as a certified language-matching service. You can use translated interfaces and optional preferences, but you should confirm the conversation language with each participant.' },
      { q: 'Does choosing a country guarantee a native speaker?', a: 'No. A country preference neither guarantees a match nor proves nationality, residence, language or fluency.' },
      { q: 'Can I practise without speaking?', a: 'Yes. Text mode supports written practice without microphone permission. Voice mode is better suited to listening and spontaneous pronunciation practice.' },
      { q: 'Are people required to correct me?', a: 'No. Ask first. Random participants are not tutors, and correction should be mutual, limited and welcome.' },
      { q: 'Do I need to share my real name or social profile?', a: 'No. Language practice does not require identifying information. Keep exact location, school, workplace and private accounts to yourself.' },
      { q: 'What if a translation is unclear?', a: 'Use the Contact page to report the exact phrase and language. For privacy, billing and legal questions, check the current official policy pages.' },
    ],
    ctaBandH: 'Practise one real conversation today',
    ctaBandP: 'Choose voice or text, agree on the language, and keep the session respectful and low-pressure.',
    cluster: 'language-learning',
    primaryIntent: 'multilingual voice chat and online speaking practice',
    relatedPages: ['practice-english-speaking', 'language-exchange', 'countries', 'safety', 'resources'],
    updated: '2026-08-14',
    posts: ['practice-english-speaking-online-free', 'how-to-start-a-conversation-with-a-stranger', 'how-to-end-a-conversation-politely'],
  },

  {
    slug: 'countries',
    crumb: 'Countries',
    eyebrow: 'Global discovery with honest limits',
    title: 'TalkLive Countries - Country Preferences for Global Voice Chat',
    description: 'Learn how TalkLive country preferences work, why a specific country match cannot be guaranteed, and how to chat respectfully with people across regions and languages.',
    keywords: 'country voice chat, talk to people worldwide, international stranger chat, global random chat, country chat preferences, chat with people from other countries',
    h1: 'Talk with People Around the World',
    lede: 'Country preferences can steer a live search, but they cannot reserve a person or prove someone’s identity, residence, nationality or language. Use them for discovery, not certainty.',
    cta: 'Start Global Voice Chat',
    ctaChat: 'Start Global Text Chat',
    featuresH: 'How country discovery really works',
    featuresIntro: 'A live queue changes every second, so useful country pages explain availability instead of manufacturing local presence.',
    features: [
      { icon: 'world', h: 'Global matching', p: 'Without a narrow preference, TalkLive can match across the live worldwide queue.' },
      { icon: 'globe', h: 'Optional preferences', p: 'Preferred and avoided country settings can guide matching within the limits shown in the product and Pricing page.' },
      { icon: 'bolt', h: 'Availability comes first', p: 'A specific country match is not guaranteed; if no preferred match is available, matching may broaden.' },
      { icon: 'chat', h: 'Language is separate', p: 'A country can contain many languages, and a flag or location label does not establish which language someone speaks.' },
      { icon: 'lock', h: 'Location stays broad', p: 'Discussing a country does not require sharing a city, neighbourhood, address, school, workplace or daily routine.' },
      { icon: 'users', h: 'No local-presence claim', p: 'TalkLive is an online global service. A country guide does not represent a physical office, local branch or guaranteed local community.' },
    ],
    stepsH: 'How to use country preferences',
    stepsIntro: 'Treat a preference as a request to the current queue, not a promise.',
    steps: [
      { h: 'Open Filters', p: 'Review the country controls and the current free or optional paid limits before searching.' },
      { h: 'Choose only what matters', p: 'Use a small, intentional list rather than narrowing the queue so far that matching becomes unlikely.' },
      { h: 'Start the live search', p: 'TalkLive looks for a compatible available participant; the chosen country may not be represented at that moment.' },
      { h: 'Broaden or try later', p: 'If availability is low, remove the preference, use global matching or return at another time.' },
    ],
    prose: [
      { h: 'A country preference is not a guarantee', body: [
        `Random matching depends on who is actively searching at the same moment and whether both participants' settings are compatible. Choosing a country can narrow that search, but it cannot create an available participant. If a preferred match is not available, TalkLive may broaden matching rather than leave the queue waiting indefinitely.`,
        `The country shown for a participant is not identity verification. Do not use it as proof of nationality, residence, citizenship or language, and do not pressure someone to reveal a city or more precise location.`,
      ]},
      { h: 'Begin with the country content that exists', body: [
        `The current focused guide is <a href="/pakistani-chat">Pakistani Chat</a>, supported by the <a href="/ur/">Urdu</a> and <a href="/hi/">Hindi</a> localized entry pages for users who prefer those interfaces. The broader <a href="/languages">Languages hub</a> lists every supported localized homepage.`,
        `Future country guides should be added only when they contain genuinely useful language, cultural, safety and product information. Replacing one place name with another does not help a user and does not establish a local TalkLive presence.`,
      ]},
      { h: 'Keep cross-cultural conversation respectful', body: [
        `Ask broad, curious questions instead of testing stereotypes: what is a normal weekend like, which food would you recommend, or what do outsiders usually misunderstand? Let the other person decide how specific to be and accept that they may not want to discuss politics, religion or personal relationships.`,
        `Country discovery still uses the same privacy rules. Do not share an address, exact workplace, school, travel itinerary, immigration documents, payments or private contact details. Review the <a href="/safety">Safety Center</a> before moving any conversation off-platform.`,
      ]},
      { h: 'Use global mode when discovery matters more than destination', body: [
        `Global matching usually gives the live queue more ways to find a compatible pair. It is the better option when your real goal is simply to hear a new perspective rather than reach one particular country. Voice supports spontaneous conversation; <a href="/random-text-chat">text chat</a> is available when you need silence or lower commitment.`,
        `For current filter allowances, friendship limits and optional paid controls, use <a href="/pricing">Pricing</a>. Country preferences do not override blocks, safety controls or the other participant's matching choices.`,
      ]},
    ],
    faq: [
      { q: 'Can TalkLive guarantee a match from a selected country?', a: 'No. Preferences depend on live availability and compatible settings. Matching may broaden when no suitable preferred-country participant is available.' },
      { q: 'Does the country label verify where someone lives?', a: 'No. It is not identity, nationality, citizenship or residence verification and should not be treated as proof.' },
      { q: 'Is a country preference also a language filter?', a: 'No. Countries are multilingual, and individuals may speak different languages. Confirm the language politely at the start of a conversation.' },
      { q: 'Why was I matched outside my preference?', a: 'Availability changes continuously, and matching may broaden rather than keep you waiting. Review your applied filters and the current product behaviour.' },
      { q: 'Does TalkLive have offices or local branches in these countries?', a: 'This hub describes an online global service and matching preferences. It does not claim a physical local office, branch or guaranteed local user community.' },
      { q: 'Should TalkLive create city pages?', a: 'Only if a page can provide genuine, distinct local utility. Generic city-name substitutions or claims of local presence would be misleading.' },
    ],
    ctaBandH: 'Open the world without over-narrowing it',
    ctaBandP: 'Use a country preference when it matters, or choose global matching for the widest live queue.',
    cluster: 'countries-and-regions',
    primaryIntent: 'country voice chat preferences and global stranger chat',
    relatedPages: ['pakistani-chat', 'languages', 'safety', 'random-voice-chat', 'random-text-chat', 'pricing'],
    updated: '2026-08-14',
    posts: ['science-of-talking-to-strangers', 'random-chat-safety-tips', 'how-to-start-a-conversation-with-a-stranger'],
  },

  {
    slug: 'how-it-works',
    crumb: 'How It Works',
    eyebrow: 'Matching, WebRTC and data',
    title: 'How TalkLive Works - Matching, WebRTC Voice & Text Chat',
    description: 'See how TalkLive matches strangers, establishes encrypted WebRTC voice calls over its production TURN relay, delivers text chat and handles privacy and moderation data.',
    keywords: 'how TalkLive works, WebRTC voice chat, random chat matching, TURN relay voice call, encrypted audio chat, stranger chat technology',
    h1: 'How TalkLive Works',
    lede: 'From pressing Talk or Chat to meeting a stranger: this is the practical path through matching, signalling, encrypted relayed media, text delivery and the controls that end a session.',
    cta: 'Try a Voice Match',
    ctaChat: 'Try a Text Match',
    featuresH: 'The system in six parts',
    featuresIntro: 'Voice and text share a matching experience, then use different paths to carry the conversation.',
    features: [
      { icon: 'users', h: 'Separate live queues', p: 'A voice search is paired with another voice participant and a text search with another text participant.' },
      { icon: 'globe', h: 'Preference-aware matching', p: 'The matcher considers compatible settings and live availability, then may broaden a search when narrow preferences cannot be fulfilled.' },
      { icon: 'mic', h: 'Encrypted WebRTC audio', p: 'Browsers negotiate an encrypted real-time audio connection after the signalling service introduces a pair.' },
      { icon: 'world', h: 'Production TURN relay', p: 'Encrypted audio packets travel through TalkLive\'s production TURN relay to support consistent connectivity.' },
      { icon: 'chat', h: 'Server-delivered text', p: 'Text messages use the service to reach the other participant and may be retained for a limited period under the Privacy Policy.' },
      { icon: 'next', h: 'User-controlled ending', p: 'Hang up, Next, block and report end the interaction; a new search starts only when you choose it.' },
    ],
    stepsH: 'From button to conversation',
    stepsIntro: 'The visible experience is simple because the browser and server divide the work.',
    steps: [
      { h: 'Choose Talk or Chat', p: 'Voice requests microphone access; text mode can begin without microphone or camera permission.' },
      { h: 'Join the matching queue', p: 'The server records the active search mode and compatible preferences while looking for another available participant.' },
      { h: 'Establish the connection', p: 'For voice, browsers exchange WebRTC connection data through signalling and establish an encrypted path through the production TURN relay.' },
      { h: 'Talk, type or leave', p: 'Continue while both people want to, then hang up, choose Next, block or report as appropriate.' },
    ],
    prose: [
      { h: 'Matching comes before media', body: [
        `When you start a search, TalkLive places the session in the queue for the mode you selected. The matcher looks for another available participant with compatible settings. Optional country and interest preferences can guide the search, but a selected country, interest, identity or language is not guaranteed.`,
        `If a narrow preference cannot be fulfilled, matching may broaden so the queue does not wait forever. The <a href="/countries">Countries hub</a> explains why a live preference cannot reserve a person from a particular place.`,
      ]},
      { h: 'Voice uses WebRTC plus signalling', body: [
        `After a voice pair is selected, the server relays signalling messages that let the two browsers negotiate formats, encryption and the relayed network path. The signalling channel coordinates the connection; it is not an audio recording channel.`,
        `WebRTC encrypts voice media in transit, and TalkLive configures production calls to use a TURN relay. TalkLive does not record or store voice audio. The other participant still controls their endpoint and may record on their own device.`,
      ]},
      { h: 'Text follows a different path', body: [
        `Text chat does not need microphone access and does not use the same real-time audio path. Messages are delivered through TalkLive's service. Typed messages, friend-chat data, reports and related context may be retained for a limited period for delivery, safety and moderation.`,
        `Retention details can change as the service evolves, so the <a href="/privacy">Privacy Policy</a> is the source of truth. Do not put passwords, authentication codes, banking details, identity documents or information that would harm you if retained into a stranger chat.`,
      ]},
      { h: 'What “not recorded” does and does not mean', body: [
        `TalkLive does not create voice recordings. That statement does not prevent the other participant from recording sound after their browser plays it. They control their endpoint, and no media protocol can stop a separate recorder in the room.`,
        `The service still handles operational information required to run and protect the platform, such as network connections, matching state and reports. Read the <a href="/safety">Safety Center</a> for practical boundaries and the <a href="/blog/how-anonymous-voice-chat-works">technical WebRTC guide</a> for a deeper explanation.`,
      ]},
      { h: 'Ending and moderation are part of the design', body: [
        `A call or chat continues only while both sessions remain connected. Hang up ends it; Next requests another match. Blocking is for preventing unwanted contact, while reporting supplies moderation information about behaviour that may violate the rules.`,
        `These controls reduce harm but do not verify strangers or make every interaction safe. TalkLive is restricted to adults, and the <a href="/terms">Terms</a> and <a href="/safety">Safety Center</a> explain the behaviour and precautions expected from users.`,
      ]},
    ],
    faq: [
      { q: 'Does TalkLive use direct peer-to-peer audio?', a: 'TalkLive configures production WebRTC calls to use a TURN relay for connectivity. The audio is encrypted in transit, and TalkLive does not record or store it.' },
      { q: 'Does TalkLive need camera permission?', a: 'No. Voice mode needs microphone permission; text mode needs neither microphone nor camera permission for a basic chat.' },
      { q: 'Does TalkLive record my voice?', a: 'No. TalkLive does not record voice calls. Another participant may still record audio on their own device, so avoid sharing sensitive information.' },
      { q: 'Are text messages retained?', a: 'Typed messages, friend-chat data, reports and related context may be retained for a limited period. See the current Privacy Policy for the authoritative details.' },
      { q: 'Why did I match outside a country preference?', a: 'Preferences depend on compatible live availability and do not guarantee a match. The search may broaden when no suitable preferred-country participant is available.' },
      { q: 'What happens when I press Next?', a: 'The current interaction ends and TalkLive starts a fresh search in the selected mode. You remain free to stop rather than enter another match.' },
    ],
    ctaBandH: 'See the system from the simple side',
    ctaBandP: 'Choose voice or text; TalkLive handles the introduction, and you stay in control of when the conversation ends.',
    cluster: 'product-and-technology',
    primaryIntent: 'how TalkLive matching and WebRTC voice chat work',
    relatedPages: ['safety', 'privacy', 'countries', 'languages', 'random-voice-chat', 'random-text-chat'],
    updated: '2026-08-14',
    posts: ['how-anonymous-voice-chat-works', 'is-talklive-safe', 'random-chat-safety-tips'],
  },
];
