process.env.STRIPE_SECRET_KEY = 'sk_test_x';
process.env.STRIPE_PRICE_MONTHLY = 'price_m';
process.env.STRIPE_PRICE_YEARLY = 'price_y';
process.env.STRIPE_WEBHOOK_SECRET = 'whsec_test';
const crypto = require('crypto');
const b = require('../server/billing');
let failed = 0;
const ok = (n, c) => { if (!c) failed++; console.log(c ? 'PASS' : 'FAIL', n); };
ok('configured', b.configured());
ok('plans', JSON.stringify(b.plans()) === '["monthly","yearly"]');
function sign(body, t = Math.floor(Date.now() / 1000), secret = 'whsec_test') {
  const v1 = crypto.createHmac('sha256', secret).update(`${t}.${body}`).digest('hex');
  return `t=${t},v1=${v1}`;
}
const body = JSON.stringify({ type: 'checkout.session.completed', data: { object: { client_reference_id: 'cid1', payment_status: 'paid', subscription: 'sub_1' } } });
ok('valid sig', !!b.verifyWebhook(body, sign(body)));
ok('wrong secret rejected', b.verifyWebhook(body, sign(body, undefined, 'whsec_other')) === null);
ok('tampered body rejected', b.verifyWebhook(body + ' ', sign(body)) === null);
ok('replay (old ts) rejected', b.verifyWebhook(body, sign(body, Math.floor(Date.now() / 1000) - 4000)) === null);
ok('missing header rejected', b.verifyWebhook(body, '') === null);
ok('short sig does not throw', b.verifyWebhook(body, 't=1,v1=ab') === null);
const d = (t) => b.decide(JSON.parse(t));
let r = d(body);
ok('checkout -> grant', r.action === 'grant' && r.clientId === 'cid1' && r.until === null);
r = d(JSON.stringify({ type: 'checkout.session.completed', data: { object: { client_reference_id: 'c', payment_status: 'unpaid' } } }));
ok('unpaid checkout ignored', r.action === 'ignore');
const end = Math.floor(Date.now() / 1000) + 2592000;
r = d(JSON.stringify({ type: 'invoice.paid', data: { object: { metadata: { clientId: 'c2' }, lines: { data: [{ period: { end } }] }, subscription: 'sub_2' } } }));
ok('invoice -> grant with period end', r.action === 'grant' && r.until === end * 1000);
r = d(JSON.stringify({ type: 'customer.subscription.updated', data: { object: { id: 's', metadata: { clientId: 'c' }, status: 'active', cancel_at_period_end: true, current_period_end: end } } }));
ok('cancel_at_period_end keeps access', r.action === 'grant' && r.until === end * 1000);
r = d(JSON.stringify({ type: 'customer.subscription.updated', data: { object: { id: 's', metadata: { clientId: 'c' }, status: 'past_due' } } }));
ok('past_due revokes', r.action === 'revoke');
r = d(JSON.stringify({ type: 'customer.subscription.deleted', data: { object: { id: 's', metadata: { clientId: 'c' } } } }));
ok('deleted revokes', r.action === 'revoke');
r = d(JSON.stringify({ type: 'invoice.paid', data: { object: {} } }));
ok('no clientId ignored', r.action === 'ignore');
r = d(JSON.stringify({ type: 'ping', data: { object: { metadata: { clientId: 'c' } } } }));
ok('unknown type ignored', r.action === 'ignore');
ok('form encode nested', b._formEncode({ a: 1, b: { c: 'd e' } }).join('&') === 'a=1&b%5Bc%5D=d%20e');
console.log(failed ? `\n${failed} FAILED` : '\nall passed');
process.exit(failed ? 1 : 0);
